package location

// Curated dataset. Extend cities/areas at runtime via LoadCities; countries +
// languages + timezones cover the common set and can be appended in a fork.
var countries = []Country{
	{"EG", "Egypt", "EGP", "+20", "Africa", "Africa/Cairo"},
	{"SA", "Saudi Arabia", "SAR", "+966", "Asia", "Asia/Riyadh"},
	{"AE", "United Arab Emirates", "AED", "+971", "Asia", "Asia/Dubai"},
	{"KW", "Kuwait", "KWD", "+965", "Asia", "Asia/Kuwait"},
	{"QA", "Qatar", "QAR", "+974", "Asia", "Asia/Qatar"},
	{"BH", "Bahrain", "BHD", "+973", "Asia", "Asia/Bahrain"},
	{"OM", "Oman", "OMR", "+968", "Asia", "Asia/Muscat"},
	{"JO", "Jordan", "JOD", "+962", "Asia", "Asia/Amman"},
	{"LB", "Lebanon", "LBP", "+961", "Asia", "Asia/Beirut"},
	{"IQ", "Iraq", "IQD", "+964", "Asia", "Asia/Baghdad"},
	{"MA", "Morocco", "MAD", "+212", "Africa", "Africa/Casablanca"},
	{"DZ", "Algeria", "DZD", "+213", "Africa", "Africa/Algiers"},
	{"TN", "Tunisia", "TND", "+216", "Africa", "Africa/Tunis"},
	{"LY", "Libya", "LYD", "+218", "Africa", "Africa/Tripoli"},
	{"SD", "Sudan", "SDG", "+249", "Africa", "Africa/Khartoum"},
	{"US", "United States", "USD", "+1", "Americas", "America/New_York"},
	{"CA", "Canada", "CAD", "+1", "Americas", "America/Toronto"},
	{"MX", "Mexico", "MXN", "+52", "Americas", "America/Mexico_City"},
	{"BR", "Brazil", "BRL", "+55", "Americas", "America/Sao_Paulo"},
	{"AR", "Argentina", "ARS", "+54", "Americas", "America/Argentina/Buenos_Aires"},
	{"GB", "United Kingdom", "GBP", "+44", "Europe", "Europe/London"},
	{"IE", "Ireland", "EUR", "+353", "Europe", "Europe/Dublin"},
	{"FR", "France", "EUR", "+33", "Europe", "Europe/Paris"},
	{"DE", "Germany", "EUR", "+49", "Europe", "Europe/Berlin"},
	{"ES", "Spain", "EUR", "+34", "Europe", "Europe/Madrid"},
	{"IT", "Italy", "EUR", "+39", "Europe", "Europe/Rome"},
	{"NL", "Netherlands", "EUR", "+31", "Europe", "Europe/Amsterdam"},
	{"BE", "Belgium", "EUR", "+32", "Europe", "Europe/Brussels"},
	{"CH", "Switzerland", "CHF", "+41", "Europe", "Europe/Zurich"},
	{"AT", "Austria", "EUR", "+43", "Europe", "Europe/Vienna"},
	{"SE", "Sweden", "SEK", "+46", "Europe", "Europe/Stockholm"},
	{"NO", "Norway", "NOK", "+47", "Europe", "Europe/Oslo"},
	{"DK", "Denmark", "DKK", "+45", "Europe", "Europe/Copenhagen"},
	{"FI", "Finland", "EUR", "+358", "Europe", "Europe/Helsinki"},
	{"PL", "Poland", "PLN", "+48", "Europe", "Europe/Warsaw"},
	{"PT", "Portugal", "EUR", "+351", "Europe", "Europe/Lisbon"},
	{"GR", "Greece", "EUR", "+30", "Europe", "Europe/Athens"},
	{"TR", "Turkey", "TRY", "+90", "Asia", "Europe/Istanbul"},
	{"RU", "Russia", "RUB", "+7", "Europe", "Europe/Moscow"},
	{"UA", "Ukraine", "UAH", "+380", "Europe", "Europe/Kyiv"},
	{"IN", "India", "INR", "+91", "Asia", "Asia/Kolkata"},
	{"PK", "Pakistan", "PKR", "+92", "Asia", "Asia/Karachi"},
	{"BD", "Bangladesh", "BDT", "+880", "Asia", "Asia/Dhaka"},
	{"CN", "China", "CNY", "+86", "Asia", "Asia/Shanghai"},
	{"JP", "Japan", "JPY", "+81", "Asia", "Asia/Tokyo"},
	{"KR", "South Korea", "KRW", "+82", "Asia", "Asia/Seoul"},
	{"ID", "Indonesia", "IDR", "+62", "Asia", "Asia/Jakarta"},
	{"MY", "Malaysia", "MYR", "+60", "Asia", "Asia/Kuala_Lumpur"},
	{"SG", "Singapore", "SGD", "+65", "Asia", "Asia/Singapore"},
	{"TH", "Thailand", "THB", "+66", "Asia", "Asia/Bangkok"},
	{"VN", "Vietnam", "VND", "+84", "Asia", "Asia/Ho_Chi_Minh"},
	{"PH", "Philippines", "PHP", "+63", "Asia", "Asia/Manila"},
	{"AU", "Australia", "AUD", "+61", "Oceania", "Australia/Sydney"},
	{"NZ", "New Zealand", "NZD", "+64", "Oceania", "Pacific/Auckland"},
	{"ZA", "South Africa", "ZAR", "+27", "Africa", "Africa/Johannesburg"},
	{"NG", "Nigeria", "NGN", "+234", "Africa", "Africa/Lagos"},
	{"KE", "Kenya", "KES", "+254", "Africa", "Africa/Nairobi"},
	{"GH", "Ghana", "GHS", "+233", "Africa", "Africa/Accra"},
	{"ET", "Ethiopia", "ETB", "+251", "Africa", "Africa/Addis_Ababa"},
}

var languages = []Language{
	{"ar", "Arabic", "العربية"}, {"en", "English", "English"}, {"fr", "French", "Français"},
	{"es", "Spanish", "Español"}, {"de", "German", "Deutsch"}, {"it", "Italian", "Italiano"},
	{"pt", "Portuguese", "Português"}, {"ru", "Russian", "Русский"}, {"tr", "Turkish", "Türkçe"},
	{"fa", "Persian", "فارسی"}, {"ur", "Urdu", "اردو"}, {"hi", "Hindi", "हिन्दी"},
	{"bn", "Bengali", "বাংলা"}, {"zh", "Chinese", "中文"}, {"ja", "Japanese", "日本語"},
	{"ko", "Korean", "한국어"}, {"id", "Indonesian", "Bahasa Indonesia"}, {"ms", "Malay", "Bahasa Melayu"},
	{"th", "Thai", "ไทย"}, {"vi", "Vietnamese", "Tiếng Việt"}, {"nl", "Dutch", "Nederlands"},
	{"sv", "Swedish", "Svenska"}, {"no", "Norwegian", "Norsk"}, {"da", "Danish", "Dansk"},
	{"fi", "Finnish", "Suomi"}, {"pl", "Polish", "Polski"}, {"el", "Greek", "Ελληνικά"},
	{"uk", "Ukrainian", "Українська"}, {"he", "Hebrew", "עברית"}, {"sw", "Swahili", "Kiswahili"},
}

var timezones = []string{
	"UTC", "Africa/Cairo", "Africa/Casablanca", "Africa/Lagos", "Africa/Nairobi", "Africa/Johannesburg",
	"America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Toronto",
	"America/Mexico_City", "America/Sao_Paulo", "America/Argentina/Buenos_Aires",
	"Asia/Riyadh", "Asia/Dubai", "Asia/Kuwait", "Asia/Qatar", "Asia/Baghdad", "Asia/Tehran",
	"Asia/Karachi", "Asia/Kolkata", "Asia/Dhaka", "Asia/Bangkok", "Asia/Jakarta", "Asia/Shanghai",
	"Asia/Hong_Kong", "Asia/Singapore", "Asia/Tokyo", "Asia/Seoul", "Asia/Kuala_Lumpur", "Asia/Manila",
	"Australia/Sydney", "Australia/Perth", "Pacific/Auckland",
	"Europe/London", "Europe/Dublin", "Europe/Paris", "Europe/Berlin", "Europe/Madrid", "Europe/Rome",
	"Europe/Amsterdam", "Europe/Zurich", "Europe/Stockholm", "Europe/Athens", "Europe/Istanbul",
	"Europe/Moscow", "Europe/Kyiv", "Europe/Warsaw", "Europe/Lisbon",
}
